

import time
from datetime import datetime
from agents.base_agent import BaseAgent

class MemoGenerationAgent(BaseAgent):
    def __init__(self):
        """
        Initializes the MemoGenerationAgent.
        """
        super().__init__(name="MemoGenerationAgent")
        print(f"{self.name} initialized.")

    def run(self, analysis_summary: str, property_address: str) -> str:
        """
        Generates a final memo from the analysis summary.

        :param analysis_summary: The summary generated by the AnalysisAgent.
        :param property_address: The address of the property for the memo header.
        :return: A string containing the final memo.
        """
        print("Generating memo...")
        time.sleep(1)  # Simulate memo generation time

        memo = self._format_memo(analysis_summary, property_address)
        
        print("Memo generation complete.")
        return memo

    def _format_memo(self, summary: str, property_address: str) -> str:
        """
        Formats the summary into a professional memo document.
        """
        today_date = datetime.now().strftime("%Y-%m-%d")
        
        memo = f"""
MEMORANDUM
-------------------------------------------------
TO:       Loan Committee
FROM:     Automated Analysis Unit
DATE:     {today_date}
SUBJECT:  Initial Deal Memo for {property_address}
-------------------------------------------------

This memo provides an initial automated analysis of the subject property. 
The information is compiled from publicly available data sources.

{summary}

--- End of Memo ---
"""
        return memo.strip()
